### ISSUE TITLE
Calculated Resolvers of Inherited Types Are Not Also Inherited

### ISSUE THREAD

**Issue by geirman** [nicolasdao/graphql-s2s#3] opened 2017-11-29 04:55 UTC
Given this type definition
```
const typeDefs = `
   type User {
      id: ID!,
      firstName: String,
      lastName: String,
      fullName: String,
    }

    type Teammate inherits User {
      teamRole: String,
    }
`
```

And this resolver
```
const resolvers = {
  Query: {
    user: (_, { id }) => getUsers(id),
  },
  User: {
    fullName: user => `${user.firstName} ${user.lastName}`,
  },
}
```

If I query for `fullName` on the Teammate type, I get `null`. To fix this, I have to duplicate all User calculated in the Teammates type as well like this...

```
const resolvers = {
  Query: {
    user: (_, { id }) => getUsers(id),
  },
  User: {
    fullName: user => `${user.firstName} ${user.lastName}`,
  },
  Teammate: {
    fullName: user => `${user.firstName} ${user.lastName}`,
  },
}
```

I'd love it if `Teammate` inherited the calculated fields of `User` as well. Is that possible?

**Comment by geirman** [comment] 2017-11-29 04:56
BTW: Thank you very much for your work. This is exactly what I needed, and I was a bit surprised that GraphQL itself did not support the concept of inheritance.

**Comment by nicolasdao** [comment] 2017-11-29 07:44
Thanks a lot for your questions @geirman . I'll have a look at this asap.

**Comment by geirman** [comment] 2017-11-29 16:05
Thanks Nicolas! I'm feeling pretty stoked about this package. I do have a couple other comments to make. I'll open other issues for those to keep things nice and tidy.

**Comment by ryanmaxwell** [comment] 2018-09-26 10:50
Hi @geirman the newer versions of apollo server (since 2 I think) allow you to pass in an option to inherit the resolvers from interfaces (It seems like the issue is more to do with the execution of the resolvers rather than the generation of the schema which is what this project provides?)

```
const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
  inheritResolversFromInterfaces: true,
});
```

**Comment by geirman** [comment] 2018-10-15 19:40
@ryanmaxwell thanks for that tip. Makes sense. I've so far not really  understood the need for interfaces since most of the examples revolve around the `ID!` field, which has limited utility IMHO, but this could be an aha moment for me if this works.

I'm not 100% sure what a working example would look like off hand. Need to research interfaces more. But thanks for the nudge in the right direction.

**Comment by purplemana** [comment] 2018-11-13 06:51
Came here looking for this. @geirman, I guess your use case should be solved with the help of [this issue's PR](https://github.com/nicolasdao/graphql-s2s/issues/18). Basically, you could rewrite your code like:

    const typeDefs = `
     interface User {
      id: ID!,
      firstName: String,
      lastName: String,
      fullName: String,
    }

    type Teammate inherits User implements User{
      teamRole: String,
    }
    `
This way `User` is still an interface and now the  `inheritResolversFromInterfaces` option will make GraphQL look for resolving concrete type properties in `User` resolver.

Hope this helps.

**Comment by nicolasdao** [comment] 2019-05-04 00:12
Closing this issue thanks to fix from @purplemana.

**Closed by nicolasdao** 2019-05-04 00:12 UTC
